// <auto-generated />
using System;
using API_Declaraciones.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Declaraciones.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20240805215925_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Declaraciones.Data.Models.Declaraciones.Articulo", b =>
                {
                    b.Property<string>("Iddt")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<int>("Nart")
                        .HasColumnType("int");

                    b.Property<string>("Cartdesc")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Cartetamrc")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Cartpayacq")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Cartpayori")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Cartpayprc")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Carttyp")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Cartuntdcl")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Cartuntest")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Codbenef")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Iddtapu")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<string>("Iespnce")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<decimal?>("Martajuded")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("Martajuinc")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("Martass")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("Martbasimp")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Martbasimp2")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("Martemma")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("Martfle")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Martfob")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Martfobdol")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("Martfrai")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("Martunitar")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int?>("Nartapu")
                        .HasColumnType("int");

                    b.Property<decimal?>("Qartbul")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("Qartkgrbrt")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal?>("Qartkgrnet")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal?>("Qartuntdcl")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("Qartuntest")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Iddt", "Nart");

                    b.ToTable("Articulos");
                });

            modelBuilder.Entity("Declaraciones.Data.Models.Declaraciones.Declaracion", b =>
                {
                    b.Property<string>("Iddt")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<string>("Cddtage")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Cddtagr")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Cddtbur")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Cddtburdst")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Cddtcirvis")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Cddtdep")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Cddtdevass")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Cddtdevfle")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Cddtdevfob")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Cddtentrep")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Cddteta")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Cddtincote")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Cddtmdetrn")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Cddtobs")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Cddtpaidst")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Cddtpayori")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Cddtpaytrn")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Cddttransp")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("Cddtver")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Dddtbae")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Dddtcancel")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Dddtechean")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Dddtoficia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Dddtrectifa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Dddtsalida")
                        .HasColumnType("datetime2");

                    b.Property<string>("Iddtext")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<string>("Iddtextr")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<string>("Iext")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Ista")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Lddtagr")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Lddtnomfod")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Lddtnomioe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Nddtart")
                        .HasColumnType("int");

                    b.Property<int?>("Nddtdelai")
                        .HasColumnType("int");

                    b.Property<string>("Nddtimmioe")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<decimal>("Qddttaxchg")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Iddt");

                    b.ToTable("Declaraciones");
                });

            modelBuilder.Entity("Declaraciones.Data.Models.Declaraciones.Liquidacion", b =>
                {
                    b.Property<string>("Iliq")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<string>("Clipnomope")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Cliqdop")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<string>("Cliqeta")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime?>("Dlippay")
                        .HasColumnType("datetime2");

                    b.Property<string>("Iddt")
                        .HasColumnType("nvarchar(17)");

                    b.Property<decimal?>("Mliq")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("Mliqgar")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Iliq");

                    b.HasIndex("Iddt");

                    b.ToTable("Liquidaciones");
                });

            modelBuilder.Entity("Declaraciones.Data.Models.Declaraciones.LiquidacionArticulo", b =>
                {
                    b.Property<string>("Iliq")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<int>("Nart")
                        .HasColumnType("int");

                    b.Property<string>("Clqatax")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Clqatyp")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<decimal>("Mlqa")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Mlqabas")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Qlqacoefic")
                        .HasColumnType("decimal(18, 6)");

                    b.HasKey("Iliq", "Nart", "Clqatax", "Clqatyp");

                    b.ToTable("LiquidacionesArticulo");
                });

            modelBuilder.Entity("Declaraciones.Data.Models.Declaraciones.Liquidacion", b =>
                {
                    b.HasOne("Declaraciones.Data.Models.Declaraciones.Declaracion", "Declaracion")
                        .WithMany()
                        .HasForeignKey("Iddt");

                    b.Navigation("Declaracion");
                });
#pragma warning restore 612, 618
        }
    }
}
